import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "../components/Header";
import Footer from "../components/Footer";
import Sidebar from "../components/Sidebar";
import { getCart } from "../lib/api";
import { Suspense } from "react";

export default async function RootLayout({ children }) {
  let cartCount = 0;
  try {
    const cart = await getCart();
    cartCount = cart.reduce((sum, item) => sum + item.quantity, 0);
  } catch {}
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 min-h-screen flex flex-col`}>
        <Header cartCount={cartCount} />
        <div className="flex flex-1 w-full max-w-7xl mx-auto">
          <Sidebar />
          <main className="flex-1 px-6 py-8">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
